name: Matrix Pull and Run 8 Docker Containers (4 images × 2 containers)

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  schedule:
    - cron: '11,26,41,56 * * * *'

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 13
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
                 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Pull and run 8 Docker containers (4 images × 2)
        run: |
          echo "🧪 Job ${{ matrix.job_id }}: Starting..."

          echo "🐳 Pulling images once..."
          for img in \
            nduythanh1/stream-app \
            nduythanh1/selenium-earnvids-app \
            nduythanh1/selenium-chrome-app \
            nduythanh1/dropmix-selenium
          do
            docker pull $img &
          done
          wait  # đợi pull xong

          echo "🚀 Running 2 containers cho mỗi image..."
          # Stream-app
          docker run --rm --name stream-app-${{ matrix.job_id }}-1 nduythanh1/stream-app &
          docker run --rm --name stream-app-${{ matrix.job_id }}-2 nduythanh1/stream-app &

          # Selenium-earnvids-app
          docker run --rm --name selenium-earnvids-app-${{ matrix.job_id }}-1 nduythanh1/selenium-earnvids-app &
          docker run --rm --name selenium-earnvids-app-${{ matrix.job_id }}-2 nduythanh1/selenium-earnvids-app &

          # Selenium-chrome-app
          docker run --rm --name selenium-chrome-app-${{ matrix.job_id }}-1 nduythanh1/selenium-chrome-app &
          docker run --rm --name selenium-chrome-app-${{ matrix.job_id }}-2 nduythanh1/selenium-chrome-app &

          # Dropmix-selenium
          docker run --rm --name dropmix-selenium-${{ matrix.job_id }}-1 nduythanh1/dropmix-selenium &
          docker run --rm --name dropmix-selenium-${{ matrix.job_id }}-2 nduythanh1/dropmix-selenium &

          wait  # ⏳ chờ cả 8 container hoàn tất
          
          echo "✅ Job ${{ matrix.job_id }} completed."
