name: Matrix Pull 3 Images and Run 6 Containers in Parallel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # ⏱ Giới hạn thời gian mỗi job

    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Pull 3 images
        run: |
          echo "🐳 Pulling images..."
          docker pull nduythanh1/stream-app &
          docker pull nduythanh1/selenium-earnvids-app &
          docker pull nduythanh1/selenium-chrome-app &
          wait

      - name: Run 6 containers (from 3 images)
        run: |
          echo "🚀 Running 6 containers in parallel..."
          
          docker run --rm --name stream-app-1-${{ matrix.job_id }} nduythanh1/stream-app &
          docker run --rm --name stream-app-2-${{ matrix.job_id }} nduythanh1/stream-app &

          docker run --rm --name selenium-earnvids-1-${{ matrix.job_id }} nduythanh1/selenium-earnvids-app &
          docker run --rm --name selenium-earnvids-2-${{ matrix.job_id }} nduythanh1/selenium-earnvids-app &

          docker run --rm --name selenium-chrome-1-${{ matrix.job_id }} nduythanh1/selenium-chrome-app &
          docker run --rm --name selenium-chrome-2-${{ matrix.job_id }} nduythanh1/selenium-chrome-app &

          wait

          echo "✅ Job ${{ matrix.job_id }} completed."
